[build]
functions = "functions" # Specifies the directory where your functions are located
# If you have a frontend, specify the build command and publish directory for it here
# command = "npm run build"
# publish = "dist" # Or 'build', 'public', etc.

[functions]
# Optional: Specify external Node.js modules that should be bundled
external_node_modules = ["express"]
# Optional: Choose a Node.js bundler (esbuild is generally recommended)
node_bundler = "esbuild"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat" # This redirects /api/your-route to your function
status = 200
force = true