[
  {
    title: "Womens Casual V-Neck T-Shirt",
    slug: "womens-casual-v-neck-t-shirt",
    quantity: 30,
    price: 18.5,
    priceAfterDiscount: 16,
    description:
      "Soft and comfortable v-neck t-shirt, short sleeves, relaxed fit",
    category: "61b2a9d869d54640ca3d7294",
    imageCover: "https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg",
  },
  {
    title: "Unisex Crew Neck Sweatshirt",
    slug: "unisex-crew-neck-sweatshirt",
    quantity: 15,
    price: 35,
    priceAfterDiscount: 30,
    description:
      "Classic crew neck sweatshirt, fleece lining, ribbed cuffs and hem",
    category: "61b2a9d869d54640ca3d7295",
    imageCover: "https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg",
  },
  {
    title: "Mens Long Sleeve Oxford Shirt",
    slug: "mens-long-sleeve-oxford-shirt",
    quantity: 25,
    price: 45,
    priceAfterDiscount: 40,
    description: "Classic oxford shirt, button-down collar, regular fit",
    category: "61b2a9d869d54640ca3d7296",
    imageCover: "https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg",
  },
  {
    title: "Womens Yoga Leggings",
    slug: "womens-yoga-leggings",
    quantity: 40,
    price: 28,
    priceAfterDiscount: 25,
    description:
      "High-waisted yoga leggings, moisture-wicking fabric, four-way stretch",
    category: "61b2a9d869d54640ca3d7297",
    imageCover: "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
  },
  {
    title: "Mens Running Shorts",
    slug: "mens-running-shorts",
    quantity: 35,
    price: 22,
    priceAfterDiscount: 20,
    description:
      "Lightweight running shorts, breathable fabric, elastic waistband",
    category: "61b2a9d869d54640ca3d7298",
    imageCover: "https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg",
  },
  {
    title: "Womens Summer Dress",
    slug: "womens-summer-dress",
    quantity: 20,
    price: 55,
    priceAfterDiscount: 50,
    description: "Flowy summer dress, floral print, spaghetti straps",
    category: "61b2a9d869d54640ca3d7299",
    imageCover: "https://example.com/images/summer-dress.jpg",
  },
  {
    title: "Mens Winter Jacket",
    slug: "mens-winter-jacket",
    quantity: 10,
    price: 95,
    priceAfterDiscount: 85,
    description: "Warm winter jacket, waterproof and windproof, hooded",
    category: "61b2a9d869d54640ca3d72a0",
    imageCover: "https://example.com/images/winter-jacket.jpg",
  },
  {
    title: "Womens Ankle Boots",
    slug: "womens-ankle-boots",
    quantity: 15,
    price: 70,
    priceAfterDiscount: 60,
    description: "Stylish ankle boots, leather upper, side zipper",
    category: "61b2a9d869d54640ca3d72a1",
    imageCover: "https://example.com/images/ankle-boots.jpg",
  },
  {
    title: "Mens Baseball Cap",
    slug: "mens-baseball-cap",
    quantity: 50,
    price: 15,
    priceAfterDiscount: 12,
    description: "Classic baseball cap, adjustable strap, embroidered logo",
    category: "61b2a9d869d54640ca3d72a2",
    imageCover: "https://example.com/images/baseball-cap.jpg",
  },
  {
    title: "Womens Knit Scarf",
    slug: "womens-knit-scarf",
    quantity: 30,
    price: 25,
    priceAfterDiscount: 20,
    description: "Warm knit scarf, soft and cozy, various colors available",
    category: "61b2a9d869d54640ca3d72a3",
    imageCover: "https://example.com/images/knit-scarf.jpg",
  },
  {
    title: "Mens Leather Belt",
    slug: "mens-leather-belt",
    quantity: 25,
    price: 30,
    priceAfterDiscount: 25,
    description: "Genuine leather belt, classic buckle, various sizes",
    category: "61b2a9d869d54640ca3d72a4",
    imageCover: "https://example.com/images/leather-belt.jpg",
  },
  {
    title: "Womens Sunglasses",
    slug: "womens-sunglasses",
    quantity: 40,
    price: 40,
    priceAfterDiscount: 35,
    description: "Stylish sunglasses, UV protection, various frame styles",
    category: "61b2a9d869d54640ca3d72a5",
    imageCover: "https://example.com/images/sunglasses.jpg",
  },
  {
    title: "Mens Watch",
    slug: "mens-watch",
    quantity: 10,
    price: 120,
    priceAfterDiscount: 100,
    description: "Classic analog watch, stainless steel band, water resistant",
    category: "61b2a9d869d54640ca3d72a6",
    imageCover: "https://example.com/images/mens-watch.jpg",
  },
];
